kg_site_home:
    path:      /
    defaults:  { _controller: KGSiteBundle:Accueil:index }

kg_site_cgu:
    path:      /cgu
    defaults:  { _controller: KGSiteBundle:Accueil:cgu }
        
kg_site_contact:
    path:      /contact
    defaults:  { _controller: KGSiteBundle:Accueil:contact }

kg_site_don:
    path:      /don
    defaults:  { _controller: KGSiteBundle:Accueil:don }
        
    