kg_beekeeping_management_add_recolte:
    path:      /{colonie_id}/ajouter-recolte
    defaults:  { _controller: KGBeekeepingManagementBundle:Recolte:add }
    requirements:
        colonie_id: \d+

kg_beekeeping_management_add_transhumance:
    path:      /{colonie_id}/ajouter-transhumance
    defaults:  { _controller: KGBeekeepingManagementBundle:Transhumance:add }
    requirements:
        colonie_id: \d+
        
kg_beekeeping_management_add_visite:
    path:      /{colonie_id}/ajouter-visite/
    defaults:  { _controller: KGBeekeepingManagementBundle:Visite:add }
    requirements:
        colonie_id: \d+
        
kg_beekeeping_management_add_tache:
    path:      /{colonie_id}/ajouter-tache/
    defaults:  { _controller: KGBeekeepingManagementBundle:Tache:add }
    requirements:
        colonie_id: \d+
        
kg_beekeeping_management_view_transhumances:
    path:      /{colonie_id}/afficher-transhumances
    defaults:  { _controller: KGBeekeepingManagementBundle:Transhumance:viewAll }
    requirements:
        colonie_id: \d+

kg_beekeeping_management_view_visites:
    path:      /{colonie_id}/afficher-visites
    defaults:  { _controller: KGBeekeepingManagementBundle:Visite:viewAll }
    requirements:
        colonie_id: \d+

kg_beekeeping_management_view_taches:
    path:      /{colonie_id}/afficher-taches
    defaults:  { _controller: KGBeekeepingManagementBundle:Tache:viewAll }
    requirements:
        colonie_id: \d+
        
kg_beekeeping_management_view_recoltes:
    path:      /{colonie_id}/afficher-recoltes
    defaults:  { _controller: KGBeekeepingManagementBundle:Recolte:viewAll }
    requirements:
        colonie_id: \d+
        
kg_beekeeping_management_view_remerages:
    path:      /{colonie_id}/afficher-remerages
    defaults:  { _controller: KGBeekeepingManagementBundle:Remerage:viewAll }
    requirements:
        colonie_id: \d+
               
kg_beekeeping_management_delete_colonie:
    path:      /{colonie_id}/supprimer-colonie
    defaults:  { _controller: KGBeekeepingManagementBundle:Colonie:delete }
    requirements:
        colonie_id: \d+        
        
kg_beekeeping_management_diviser_colonie:
    path:      /{colonie_id}/diviser-colonie
    defaults:  { _controller: KGBeekeepingManagementBundle:Colonie:diviser }
    requirements:
        colonie_id: \d+

kg_beekeeping_management_add_remerage:
    path:      /{colonie_id}/ajouter-remerage
    defaults:  { _controller: KGBeekeepingManagementBundle:Remerage:add }
    requirements:
        colonie_id: \d+
        
kg_beekeeping_management_tuer_colonie:
    path:      /{colonie_id}/tuer-colonie
    defaults:  { _controller: KGBeekeepingManagementBundle:Colonie:tuer }
    requirements:
        colonie_id: \d+         