kg_beekeeping_management_home:
    path:      /afficher-exploitation
    defaults:  { _controller: KGBeekeepingManagementBundle:Exploitation:viewFirst }
        
kg_beekeeping_management_add_exploitation:
    path:      /creer-exploitation
    defaults:  { _controller: KGBeekeepingManagementBundle:Exploitation:add }
       
kg_beekeeping_management_update_exploitation:
    path:      /{exploitation_id}/modifier-exploitation/
    defaults:  { _controller: KGBeekeepingManagementBundle:Exploitation:update }
    requirements:
        exploitation_id: \d+
        
kg_beekeeping_management_view_exploitation:
    path:      /{exploitation_id}/afficher-exploitation/
    defaults:  { _controller: KGBeekeepingManagementBundle:Exploitation:view}
    requirements:
        exploitation_id: \d+
        
kg_beekeeping_management_delete_exploitation:
    path:      /{exploitation_id}/supprimer-exploitation/
    defaults:  { _controller: KGBeekeepingManagementBundle:Exploitation:delete }
    requirements:
        exploitation_id: \d+  
        
kg_beekeeping_management_add_rucher:
    path:      /{exploitation_id}/ajouter-rucher
    defaults:  { _controller: KGBeekeepingManagementBundle:Rucher:add }
    requirements:
        exploitation_id: \d+    
        
kg_beekeeping_management_add_collaborateur:
    path:      /{exploitation_id}/ajouter-collaborateur
    defaults:  { _controller: KGBeekeepingManagementBundle:Exploitation:addCollab }  
    requirements:
        exploitation_id: \d+   
        
kg_beekeeping_management_delete_collaborateur:
    path:      /{apiculteurExploitation_id}/supprimer-collaborateur/
    defaults:  { _controller: KGBeekeepingManagementBundle:Exploitation:deleteCollab }
    requirements:
        apiculteurExploitation_id: \d+      
        
kg_beekeeping_management_update_collaborateur:
    path:      /{apiculteurExploitation_id}/modifier-collaborateur/
    defaults:  { _controller: KGBeekeepingManagementBundle:Exploitation:updateCollab }
    requirements:
        apiculteurExploitation_id: \d+     
        
kg_beekeeping_management_accepter_collaborateur:
    path:      /{apiculteurExploitation_id}/accepter-collaborateur/
    defaults:  { _controller: KGBeekeepingManagementBundle:Exploitation:accepterCollab }
    requirements:
        apiculteurExploitation_id: \d+            