kg_beekeeping_management_home:
    path:      /afficher-exploitation/{page}
    defaults:  { _controller: KGBeekeepingManagementBundle:Exploitation:viewEmplacements, page: 1 }
        
kg_beekeeping_management_add_exploitation:
    path:      /creer-exploitation
    defaults:  { _controller: KGBeekeepingManagementBundle:Exploitation:add }
       
kg_beekeeping_management_update_exploitation:
    path:      /{exploitation_id}/modifier-exploitation/
    defaults:  { _controller: KGBeekeepingManagementBundle:Exploitation:update }
    requirements:
        exploitation_id: \d+

kg_beekeeping_management_view_exploitation:
    path:      /{exploitation_id}/afficher-exploitation/{page}
    defaults:  { _controller: KGBeekeepingManagementBundle:Exploitation:viewEmplacements, page: 1}
    requirements:
        exploitation_id: \d+

kg_beekeeping_management_view_exploitation_taches:
    path:      /{exploitation_id}/afficher-exploitation-taches/{page}
    defaults:  { _controller: KGBeekeepingManagementBundle:Exploitation:viewTaches, page: 1}
    requirements:
        exploitation_id: \d+

kg_beekeeping_management_view_exploitation_taches_urgentes:
    path:      /{exploitation_id}/afficher-exploitation-taches-urgentes/{page}
    defaults:  { _controller: KGBeekeepingManagementBundle:Exploitation:viewTachesUrgentes, page: 1}
    requirements:
        exploitation_id: \d+
        
kg_beekeeping_management_delete_exploitation:
    path:      /{exploitation_id}/supprimer-exploitation/
    defaults:  { _controller: KGBeekeepingManagementBundle:Exploitation:delete }
    requirements:
        exploitation_id: \d+  
        
kg_beekeeping_management_add_rucher:
    path:      /{exploitation_id}/ajouter-rucher
    defaults:  { _controller: KGBeekeepingManagementBundle:Rucher:add }
    requirements:
        exploitation_id: \d+        