kg_beekeeping_management_update_rucher:
    path:      /{rucher_id}/modifier-rucher
    defaults:  { _controller: KGBeekeepingManagementBundle:Rucher:update }
    requirements:
        rucher_id: \d+
        
kg_beekeeping_management_delete_rucher:
    path:      /{rucher_id}/supprimer-rucher
    defaults:  { _controller: KGBeekeepingManagementBundle:Rucher:delete }
    requirements:
        rucher_id: \d+
        
kg_beekeeping_management_view_rucher:
    path:      /{rucher_id}/afficher-rucher/{page}
    defaults:  { _controller: KGBeekeepingManagementBundle:Rucher:view, page: 1 }
    requirements:
        rucher_id: \d+

kg_beekeeping_management_view_colonies_mortes:
    path:      /{rucher_id}/afficher-colonies-mortes/{page}
    defaults:  { _controller: KGBeekeepingManagementBundle:Rucher:viewColoniesMortes, page: 1 }
    requirements:
        rucher_id: \d+
        
kg_beekeeping_management_add_emplacement:
    path:      /{rucher_id}/ajouter-emplacement/
    defaults:  { _controller: KGBeekeepingManagementBundle:Emplacement:add }
    requirements:
        rucher_id: \d+        