kg_beekeeping_management_update_rucher:
    path:      /{rucher_id}/modifier-rucher
    defaults:  { _controller: KGBeekeepingManagementBundle:Rucher:update }
    requirements:
        rucher_id: \d+
        
kg_beekeeping_management_delete_rucher:
    path:      /{rucher_id}/supprimer-rucher
    defaults:  { _controller: KGBeekeepingManagementBundle:Rucher:delete }
    requirements:
        rucher_id: \d+
        
kg_beekeeping_management_view_rucher:
    path:      /{rucher_id}/afficher-rucher
    defaults:  { _controller: KGBeekeepingManagementBundle:Rucher:view }
    requirements:
        rucher_id: \d+

kg_beekeeping_management_print_all_qr_code:
    path:      /{rucher_id}/imprimer-qr_code
    defaults:  { _controller: KGBeekeepingManagementBundle:Rucher:printQRCode }
    requirements:
        rucher_id: \d+
        
kg_beekeeping_management_view_colonies_mortes:
    path:      /{rucher_id}/afficher-colonies-mortes
    defaults:  { _controller: KGBeekeepingManagementBundle:Rucher:viewColoniesMortes }
    requirements:
        rucher_id: \d+
        
kg_beekeeping_management_add_emplacement:
    path:      /{rucher_id}/ajouter-emplacement/
    defaults:  { _controller: KGBeekeepingManagementBundle:Emplacement:add }
    requirements:
        rucher_id: \d+        