kg_beekeeping_management_update_tache:
    path:      /{tache_id}/modifier-tache
    defaults:  { _controller: KGBeekeepingManagementBundle:Tache:update }
    requirements:
        tache_id: \d+
        
kg_beekeeping_management_delete_tache:
    path:      /{tache_id}/supprimer-tache
    defaults:  { _controller: KGBeekeepingManagementBundle:Tache:delete }
    requirements:
        tache_id: \d+
                
kg_beekeeping_management_duplicate_tache:
    path:      /{tache_id}/{rucher_id}/dupliquer-tache
    defaults:  { _controller: KGBeekeepingManagementBundle:Tache:duplicate }
    requirements:
        tache_id: \d+  
        rucher_id: \d+ 