kg_beekeeping_management_update_visite:
    path:      /{visite_id}/modifier-visite
    defaults:  { _controller: KGBeekeepingManagementBundle:Visite:update }
    requirements:
        visite_id: \d+
        
kg_beekeeping_management_delete_visite:
    path:      /{visite_id}/supprimer-visite
    defaults:  { _controller: KGBeekeepingManagementBundle:Visite:delete }
    requirements:
        visite_id: \d+
        
kg_beekeeping_management_view_visite:
    path:      /{visite_id}/afficher-visite
    defaults:  { _controller: KGBeekeepingManagementBundle:Visite:view }
    requirements:
        visite_id: \d+ 

         