# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.chart.data:
        class: KG\BeekeepingManagementBundle\Chart\ChartData
        arguments: ['@security.context']

    app.chart:
        class: KG\BeekeepingManagementBundle\Chart\Chart
        arguments: ['@app.chart.data']