kg_advert_delete_user:
    path:      /avertissement-supprimer-compte
    defaults:  { _controller: KGUserBundle:User:advertDeleteUser }

kg_delete_user:
    path:      /supprimer
    defaults:  { _controller: KGUserBundle:User:deleteUser }
        
    