kg_beekeeping_management_home:
    path:      /index
    defaults:  { _controller: KGBeekeepingManagementBundle:Accueil:index, page: 1 }
        
kg_beekeeping_management_add_exploitation:
    path:      /exploitation/creer-exploitation
    defaults:  { _controller: KGBeekeepingManagementBundle:Exploitation:add }
       
kg_beekeeping_management_view_exploitation:
    path:      /exploitation/{exploitation_id}/affichage-exploitation/{page}
    defaults:  { _controller: KGBeekeepingManagementBundle:Exploitation:view, page: 1 }
    requirements:
        exploitation_id: \d+
           
kg_beekeeping_management_add_rucher:
    path:      /exploitation/{exploitation_id}/rucher/creer-rucher
    defaults:  { _controller: KGBeekeepingManagementBundle:Rucher:add }
    requirements:
        exploitation_id: \d+
        
kg_beekeeping_management_delete_rucher:
    path:      /exploitation/rucher/{rucher_id}/supprimer-rucher
    defaults:  { _controller: KGBeekeepingManagementBundle:Rucher:delete }
    requirements:
        rucher_id: \d+
        
kg_beekeeping_management_view_rucher:
    path:      /exploitation/rucher/{rucher_id}/affichage-rucher/{page}
    defaults:  { _controller: KGBeekeepingManagementBundle:Rucher:view, page: 1 }
    requirements:
        rucher_id: \d+

kg_beekeeping_management_add_ruche:
    path:      /exploitation/rucher/{rucher_id}/ruche/creer-ruche/
    defaults:  { _controller: KGBeekeepingManagementBundle:Ruche:add }
    requirements:
        rucher_id: \d+
        
kg_beekeeping_management_delete_ruche:
    path:      /exploitation/rucher/ruche/{ruche_id}/supprimer-ruche
    defaults:  { _controller: KGBeekeepingManagementBundle:Ruche:delete }
    requirements:
        ruche_id: \d+
        
kg_beekeeping_management_view_ruche:
    path:      /exploitation/rucher/ruche/{ruche_id}/affichage-ruche
    defaults:  { _controller: KGBeekeepingManagementBundle:Ruche:view }
    requirements:
        ruche_id: \d+