kg_beekeeping_management_home:
    path:      /manager
    defaults:  { _controller: KGBeekeepingManagementBundle:Accueil:index, page: 1 }
        
kg_beekeeping_management_add_exploitation:
    path:      /exploitation/creer-exploitation
    defaults:  { _controller: KGBeekeepingManagementBundle:Exploitation:add }
       
kg_beekeeping_management_view_exploitation:
    path:      /exploitation/{exploitation_id}/afficher-exploitation/rucher/{page}
    defaults:  { _controller: KGBeekeepingManagementBundle:Exploitation:viewRucher, page: 1 }
    requirements:
        exploitation_id: \d+

kg_beekeeping_management_update_exploitation:
    path:      /exploitation/{exploitation_id}/modifier-exploitation/
    defaults:  { _controller: KGBeekeepingManagementBundle:Exploitation:update }
    requirements:
        exploitation_id: \d+
        
kg_beekeeping_management_delete_exploitation:
    path:      /exploitation/{exploitation_id}/supprimer-exploitation/
    defaults:  { _controller: KGBeekeepingManagementBundle:Exploitation:delete }
    requirements:
        exploitation_id: \d+
        
kg_beekeeping_management_view_exploitation_colonnie:
    path:      /exploitation/{exploitation_id}/afficher-exploitation/colonnie/{page}
    defaults:  { _controller: KGBeekeepingManagementBundle:Exploitation:viewColonnie, page: 1 }
    requirements:
        exploitation_id: \d+

kg_beekeeping_management_view_exploitation_ruche:
    path:      /exploitation/{exploitation_id}/afficher-exploitation/ruche/{page}
    defaults:  { _controller: KGBeekeepingManagementBundle:Exploitation:viewRuche, page: 1 }
    requirements:
        exploitation_id: \d+
        
kg_beekeeping_management_add_rucher:
    path:      /exploitation/{exploitation_id}/rucher/creer-rucher
    defaults:  { _controller: KGBeekeepingManagementBundle:Rucher:add }
    requirements:
        exploitation_id: \d+
        
kg_beekeeping_management_update_rucher:
    path:      /exploitation/rucher/{rucher_id}/modifier-rucher
    defaults:  { _controller: KGBeekeepingManagementBundle:Rucher:update }
    requirements:
        rucher_id: \d+
        
kg_beekeeping_management_delete_rucher:
    path:      /exploitation/rucher/{rucher_id}/supprimer-rucher
    defaults:  { _controller: KGBeekeepingManagementBundle:Rucher:delete }
    requirements:
        rucher_id: \d+
        
kg_beekeeping_management_view_rucher:
    path:      /exploitation/rucher/{rucher_id}/afficher-rucher/{page}
    defaults:  { _controller: KGBeekeepingManagementBundle:Rucher:view, page: 1 }
    requirements:
        rucher_id: \d+

kg_beekeeping_management_add_ruche_from_exploitation:
    path:      /exploitation/{exploitation_id}/ruche/creer-ruche/
    defaults:  { _controller: KGBeekeepingManagementBundle:Ruche:addFromExploitation }
    requirements:
        exploitation_id: \d+     

kg_beekeeping_management_update_ruche:
    path:      /exploitation/rucher/ruche/{ruche_id}/modifier-ruche
    defaults:  { _controller: KGBeekeepingManagementBundle:Ruche:update }
    requirements:
        ruche_id: \d+
        
kg_beekeeping_management_delete_ruche:
    path:      /exploitation/rucher/ruche/{ruche_id}/supprimer-ruche
    defaults:  { _controller: KGBeekeepingManagementBundle:Ruche:delete }
    requirements:
        ruche_id: \d+
        
kg_beekeeping_management_view_ruche:
    path:      /exploitation/rucher/ruche/{ruche_id}/afficher-ruche/{page}
    defaults:  { _controller: KGBeekeepingManagementBundle:Ruche:view, page: 1 }
    requirements:
        ruche_id: \d+

kg_beekeeping_management_transhumer_ruche:
    path:      /exploitation/ruche/{ruche_id}/transhumer-ruche
    defaults:  { _controller: KGBeekeepingManagementBundle:Ruche:transhumer }
    requirements:
        ruche_id: \d+
        
kg_beekeeping_management_add_visite:
    path:      /exploitation/rucher/ruche/colonnie/{colonnie_id}/creer-visite/
    defaults:  { _controller: KGBeekeepingManagementBundle:Visite:add }
    requirements:
        ruche_id: \d+
        
kg_beekeeping_management_delete_visite:
    path:      /exploitation/rucher/ruche/colonnie/visite/{visite_id}/supprimer-visite
    defaults:  { _controller: KGBeekeepingManagementBundle:Visite:delete }
    requirements:
        visite_id: \d+
        
kg_beekeeping_management_view_visite:
    path:      /exploitation/rucher/ruche/colonnie/visite/{visite_id}/afficher-visite
    defaults:  { _controller: KGBeekeepingManagementBundle:Visite:view }
    requirements:
        visite_id: \d+ 
        
kg_beekeeping_management_add_colonnie:
    path:      /exploitation/{exploitation_id}/colonnie/creer-colonnie
    defaults:  { _controller: KGBeekeepingManagementBundle:Colonnie:add }
    requirements:
        exploitation_id: \d+
        
kg_beekeeping_management_delete_colonnie:
    path:      /exploitation/colonnie/{colonnie_id}/supprimer-colonnie
    defaults:  { _controller: KGBeekeepingManagementBundle:Colonnie:delete }
    requirements:
        colonnie_id: \d+

kg_beekeeping_management_update_colonnie:
    path:      /exploitation/colonnie/{colonnie_id}/modifier-colonnie
    defaults:  { _controller: KGBeekeepingManagementBundle:Colonnie:update }
    requirements:
        colonnie_id: \d+      

kg_beekeeping_management_view_colonnie:
    path:      /exploitation/colonnie/{colonnie_id}/afficher-colonnie
    defaults:  { _controller: KGBeekeepingManagementBundle:Colonnie:view }
    requirements:
        colonnie_id: \d+         
        
kg_beekeeping_management_diviser_colonnie:
    path:      /exploitation/colonnie/{colonnie_id}/diviser-colonnie
    defaults:  { _controller: KGBeekeepingManagementBundle:Colonnie:diviser }
    requirements:
        colonnie_id: \d+

kg_beekeeping_management_renouveler_reine:
    path:      /exploitation/colonnie/reine/{reine_id}/renouveler-reine
    defaults:  { _controller: KGBeekeepingManagementBundle:Reine:renouveler }
    requirements:
        reine_id: \d+
        
kg_beekeeping_management_enrucher_colonnie:
    path:      /exploitation/colonnie/{colonnie_id}/enrucher-colonnie
    defaults:  { _controller: KGBeekeepingManagementBundle:Colonnie:enrucher }
    requirements:
        colonnie_id: \d+

kg_beekeeping_management_select_ruches_colonnie:
    path:      /exploitation/colonnie/select_ruches-colonnie
    defaults:  { _controller: KGBeekeepingManagementBundle:Colonnie:ruches }
    options:
        expose: true    

kg_beekeeping_management_select_emplacements_ruche:
    path:      /exploitation/ruche/select_emplacements-ruche
    defaults:  { _controller: KGBeekeepingManagementBundle:Ruche:emplacements }
    options:
        expose: true
        
kg_beekeeping_management_tuer_colonnie:
    path:      /exploitation/colonnie/{colonnie_id}/tuer-colonnie
    defaults:  { _controller: KGBeekeepingManagementBundle:Colonnie:tuer }
    requirements:
        colonnie_id: \d+ 
        
kg_beekeeping_management_add_emplacement:
    path:      /exploitation/rucher/{rucher_id}/creer-emplacement/
    defaults:  { _controller: KGBeekeepingManagementBundle:Emplacement:add }
    requirements:
        ruche_id: \d+
        
kg_beekeeping_management_delete_emplacement:
    path:      /exploitation/rucher/emplacement/{emplacement_id}/supprimer-emplacement
    defaults:  { _controller: KGBeekeepingManagementBundle:Emplacement:delete }
    requirements:
        visite_id: \d+
        
kg_beekeeping_management_view_emplacement:
    path:      /exploitation/rucher/emplacement/{emplacement_id}/afficher-emplacement
    defaults:  { _controller: KGBeekeepingManagementBundle:Emplacement:view }
    requirements:
        visite_id: \d+   
        
kg_beekeeping_management_update_emplacement:
    path:      /exploitation/rucher/emplacement/{emplacement_id}/modifier-emplacement
    defaults:  { _controller: KGBeekeepingManagementBundle:Emplacement:update }
    requirements:
        colonnie_id: \d+              