kg_beekeeping_management_home:
    path:      /manager
    defaults:  { _controller: KGBeekeepingManagementBundle:Accueil:index }
        
kg_beekeeping_management_add_exploitation:
    path:      /exploitation/creer-exploitation
    defaults:  { _controller: KGBeekeepingManagementBundle:Exploitation:add }
       
kg_beekeeping_management_update_exploitation:
    path:      /exploitation/{exploitation_id}/modifier-exploitation/
    defaults:  { _controller: KGBeekeepingManagementBundle:Exploitation:update }
    requirements:
        exploitation_id: \d+
        
kg_beekeeping_management_delete_exploitation:
    path:      /exploitation/{exploitation_id}/supprimer-exploitation/
    defaults:  { _controller: KGBeekeepingManagementBundle:Exploitation:delete }
    requirements:
        exploitation_id: \d+
                
kg_beekeeping_management_add_rucher:
    path:      /exploitation/{exploitation_id}/rucher/creer-rucher
    defaults:  { _controller: KGBeekeepingManagementBundle:Rucher:add }
    requirements:
        exploitation_id: \d+
        
kg_beekeeping_management_update_rucher:
    path:      /exploitation/rucher/{rucher_id}/modifier-rucher
    defaults:  { _controller: KGBeekeepingManagementBundle:Rucher:update }
    requirements:
        rucher_id: \d+
        
kg_beekeeping_management_delete_rucher:
    path:      /exploitation/rucher/{rucher_id}/supprimer-rucher
    defaults:  { _controller: KGBeekeepingManagementBundle:Rucher:delete }
    requirements:
        rucher_id: \d+
        
kg_beekeeping_management_view_rucher:
    path:      /exploitation/rucher/{rucher_id}/afficher-rucher/{page}
    defaults:  { _controller: KGBeekeepingManagementBundle:Rucher:view, page: 1 }
    requirements:
        rucher_id: \d+

kg_beekeeping_management_add_ruche:
    path:      /exploitation/rucher/emplacement/{emplacement_id}/ruche/creer-ruche/
    defaults:  { _controller: KGBeekeepingManagementBundle:Ruche:add }
    requirements:
        emplacement_id: \d+     

kg_beekeeping_management_update_ruche:
    path:      /exploitation/rucher/ruche/{ruche_id}/modifier-ruche
    defaults:  { _controller: KGBeekeepingManagementBundle:Ruche:update }
    requirements:
        ruche_id: \d+
                
kg_beekeeping_management_view_ruche:
    path:      /exploitation/rucher/ruche/{ruche_id}/afficher-ruche/{page}
    defaults:  { _controller: KGBeekeepingManagementBundle:Ruche:view, page: 1 }
    requirements:
        ruche_id: \d+

kg_beekeeping_management_add_hausse:
    path:      /exploitation/rucher/ruche/{ruche_id}/ajouter-hausse
    defaults:  { _controller: KGBeekeepingManagementBundle:Ruche:addHausse}
    requirements:
        ruche_id: \d+

kg_beekeeping_management_delete_hausse:
    path:      /exploitation/rucher/ruche/{ruche_id}/supprimer-hausse
    defaults:  { _controller: KGBeekeepingManagementBundle:Ruche:deleteHausse}
    requirements:
        ruche_id: \d+
        
kg_beekeeping_management_transhumer_ruche:
    path:      /exploitation/ruche/{ruche_id}/transhumer-ruche
    defaults:  { _controller: KGBeekeepingManagementBundle:Ruche:transhumer }
    requirements:
        ruche_id: \d+
        
kg_beekeeping_management_add_visite:
    path:      /exploitation/rucher/ruche/colonie/{colonie_id}/creer-visite/
    defaults:  { _controller: KGBeekeepingManagementBundle:Visite:add }
    requirements:
        ruche_id: \d+

kg_beekeeping_management_update_visite:
    path:      /exploitation/rucher/ruche/colonie/visite/{visite_id}/modifier-visite
    defaults:  { _controller: KGBeekeepingManagementBundle:Visite:update }
    requirements:
        visite_id: \d+
        
kg_beekeeping_management_delete_visite:
    path:      /exploitation/rucher/ruche/colonie/visite/{visite_id}/supprimer-visite
    defaults:  { _controller: KGBeekeepingManagementBundle:Visite:delete }
    requirements:
        visite_id: \d+
        
kg_beekeeping_management_view_visite:
    path:      /exploitation/rucher/ruche/colonie/visite/{visite_id}/afficher-visite
    defaults:  { _controller: KGBeekeepingManagementBundle:Visite:view }
    requirements:
        visite_id: \d+ 
               
kg_beekeeping_management_delete_colonie:
    path:      /exploitation/colonie/{colonie_id}/supprimer-colonie
    defaults:  { _controller: KGBeekeepingManagementBundle:Colonie:delete }
    requirements:
        colonie_id: \d+

kg_beekeeping_management_update_colonie:
    path:      /exploitation/colonie/{colonie_id}/modifier-colonie
    defaults:  { _controller: KGBeekeepingManagementBundle:Colonie:update }
    requirements:
        colonie_id: \d+      

kg_beekeeping_management_view_colonie:
    path:      /exploitation/colonie/{colonie_id}/afficher-colonie
    defaults:  { _controller: KGBeekeepingManagementBundle:Colonie:view }
    requirements:
        colonie_id: \d+         
        
kg_beekeeping_management_diviser_colonie:
    path:      /exploitation/colonie/{colonie_id}/diviser-colonie
    defaults:  { _controller: KGBeekeepingManagementBundle:Colonie:diviser }
    requirements:
        colonie_id: \d+

kg_beekeeping_management_renouveler_reine:
    path:      /exploitation/colonie/reine/{reine_id}/renouveler-reine
    defaults:  { _controller: KGBeekeepingManagementBundle:Reine:renouveler }
    requirements:
        reine_id: \d+
        
kg_beekeeping_management_enrucher_colonie:
    path:      /exploitation/colonie/{colonie_id}/enrucher-colonie
    defaults:  { _controller: KGBeekeepingManagementBundle:Colonie:enrucher }
    requirements:
        colonie_id: \d+ 

kg_beekeeping_management_select_emplacements_ruche:
    path:      /exploitation/ruche/select_emplacements-ruche
    defaults:  { _controller: KGBeekeepingManagementBundle:Ruche:emplacements }
    options:
        expose: true
        
kg_beekeeping_management_select_soustypes_ruche:        
    path:      /exploitation/ruche/select_soustypes-ruche
    defaults:  { _controller: KGBeekeepingManagementBundle:Ruche:soustypes }
    options:
        expose: true    
        
kg_beekeeping_management_tuer_colonie:
    path:      /exploitation/colonie/{colonie_id}/tuer-colonie
    defaults:  { _controller: KGBeekeepingManagementBundle:Colonie:tuer }
    requirements:
        colonie_id: \d+ 
        
kg_beekeeping_management_add_emplacement:
    path:      /exploitation/rucher/{rucher_id}/creer-emplacement/
    defaults:  { _controller: KGBeekeepingManagementBundle:Emplacement:add }
    requirements:
        ruche_id: \d+
        
kg_beekeeping_management_delete_emplacement:
    path:      /exploitation/rucher/emplacement/{emplacement_id}/supprimer-emplacement
    defaults:  { _controller: KGBeekeepingManagementBundle:Emplacement:delete }
    requirements:
        visite_id: \d+
        
kg_beekeeping_management_view_emplacement:
    path:      /exploitation/rucher/emplacement/{emplacement_id}/afficher-emplacement
    defaults:  { _controller: KGBeekeepingManagementBundle:Emplacement:view }
    requirements:
        visite_id: \d+   
        
kg_beekeeping_management_update_emplacement:
    path:      /exploitation/rucher/emplacement/{emplacement_id}/modifier-emplacement
    defaults:  { _controller: KGBeekeepingManagementBundle:Emplacement:update }
    requirements:
        colonie_id: \d+              