kg_beekeeping_management_home:
    path:      /index
    defaults:  { _controller: KGBeekeepingManagementBundle:Accueil:index, page: 1 }
        
kg_beekeeping_management_add_exploitation:
    path:      /exploitation/nouvelle-exploitation
    defaults:  { _controller: KGBeekeepingManagementBundle:Exploitation:add }
       
kg_beekeeping_management_view_exploitation:
    path:      /exploitation/affichage-exploitation/{page}/{exploitation_id}
    defaults:  { _controller: KGBeekeepingManagementBundle:Exploitation:view, page: 1 }
    requirements:
        exploitation_id: \d+
    
kg_beekeeping_management_menu_exploitation:
    path:      /exploitation/menu-exploitation
    defaults:  { _controller: KGBeekeepingManagementBundle:Exploitation:menu }
           
kg_beekeeping_management_add_rucher:
    path:      /rucher/nouveau-rucher
    defaults:  { _controller: KGBeekeepingManagementBundle:Rucher:add }

kg_beekeeping_management_delete_rucher:
    path:      /rucher/supprimer-rucher/{id}
    defaults:  { _controller: KGBeekeepingManagementBundle:Rucher:delete }
    requirements:
        id: \d+
        
kg_beekeeping_management_view_rucher:
    path:      /rucher/affichage-rucher/{id}
    defaults:  { _controller: KGBeekeepingManagementBundle:Rucher:view }
    requirements:
        id: \d+
    