kg_beekeeping_management_home:
    path:      /index
    defaults:  { _controller: KGBeekeepingManagementBundle:Accueil:index, page: 1 }
        
kg_beekeeping_management_add_exploitation:
    path:      /exploitation/creer-exploitation
    defaults:  { _controller: KGBeekeepingManagementBundle:Exploitation:add }
       
kg_beekeeping_management_view_exploitation:
    path:      /exploitation/{exploitation_id}/afficher-exploitation/rucher/{page}
    defaults:  { _controller: KGBeekeepingManagementBundle:Exploitation:viewRucher, page: 1 }
    requirements:
        exploitation_id: \d+

kg_beekeeping_management_view_exploitation_colonnie:
    path:      /exploitation/{exploitation_id}/afficher-exploitation/colonnie/{page}
    defaults:  { _controller: KGBeekeepingManagementBundle:Exploitation:viewColonnie, page: 1 }
    requirements:
        exploitation_id: \d+
        
kg_beekeeping_management_add_rucher:
    path:      /exploitation/{exploitation_id}/rucher/creer-rucher
    defaults:  { _controller: KGBeekeepingManagementBundle:Rucher:add }
    requirements:
        exploitation_id: \d+
        
kg_beekeeping_management_delete_rucher:
    path:      /exploitation/rucher/{rucher_id}/supprimer-rucher
    defaults:  { _controller: KGBeekeepingManagementBundle:Rucher:delete }
    requirements:
        rucher_id: \d+
        
kg_beekeeping_management_view_rucher:
    path:      /exploitation/rucher/{rucher_id}/afficher-rucher/{page}
    defaults:  { _controller: KGBeekeepingManagementBundle:Rucher:view, page: 1 }
    requirements:
        rucher_id: \d+

kg_beekeeping_management_add_ruche:
    path:      /exploitation/rucher/{rucher_id}/ruche/creer-ruche/
    defaults:  { _controller: KGBeekeepingManagementBundle:Ruche:add }
    requirements:
        rucher_id: \d+
        
kg_beekeeping_management_delete_ruche:
    path:      /exploitation/rucher/ruche/{ruche_id}/supprimer-ruche
    defaults:  { _controller: KGBeekeepingManagementBundle:Ruche:delete }
    requirements:
        ruche_id: \d+
        
kg_beekeeping_management_view_ruche:
    path:      /exploitation/rucher/ruche/{ruche_id}/afficher-ruche/{page}
    defaults:  { _controller: KGBeekeepingManagementBundle:Ruche:view, page: 1 }
    requirements:
        ruche_id: \d+
        
kg_beekeeping_management_add_visite:
    path:      /exploitation/rucher/ruche/{ruche_id}/creer-visite/
    defaults:  { _controller: KGBeekeepingManagementBundle:Visite:add }
    requirements:
        rucher_id: \d+
        
kg_beekeeping_management_delete_visite:
    path:      /exploitation/rucher/ruche/visite/{visite_id}/supprimer-visite
    defaults:  { _controller: KGBeekeepingManagementBundle:Visite:delete }
    requirements:
        ruche_id: \d+
        
kg_beekeeping_management_view_visite:
    path:      /exploitation/rucher/ruche/visite/{visite_id}/afficher-visite
    defaults:  { _controller: KGBeekeepingManagementBundle:Visite:view }
    requirements:
        ruche_id: \d+ 
        
kg_beekeeping_management_add_colonnie:
    path:      /exploitation/{exploitation_id}/colonnie/creer-colonnie
    defaults:  { _controller: KGBeekeepingManagementBundle:Colonnie:add }
    requirements:
        exploitation_id: \d+
        
kg_beekeeping_management_delete_colonnie:
    path:      /exploitation/colonnie/{colonnie_id}/supprimer-colonnie
    defaults:  { _controller: KGBeekeepingManagementBundle:Colonnie:delete }
    requirements:
        rucher_id: \d+
        
kg_beekeeping_management_view_colonnie:
    path:      /exploitation/colonnie/{colonnie_id}/afficher-colonnie/{page}
    defaults:  { _controller: KGBeekeepingManagementBundle:Colonnie:view, page: 1 }
    requirements:
        rucher_id: \d+        