kg_beekeeping_management_home_rucher:
    path:      /rucher/{page}
    defaults:  { _controller: KGBeekeepingManagementBundle:Rucher:index, page: 1 }
    requirements:
        page:  \d+
        
kg_beekeeping_management_add_rucher:
    path:      /rucher/nouveau-rucher
    defaults:  { _controller: KGBeekeepingManagementBundle:Rucher:add }
    
kg_beekeeping_management_view_rucher:
    path:      /rucher/affichage-rucher/{id}
    defaults:  { _controller: KGBeekeepingManagementBundle:Rucher:view }
    requirements:
        id: \d+

kg_beekeeping_management_home_lieuStock:
    path:      /lieuStock/{page}
    defaults:  { _controller: KGBeekeepingManagementBundle:LieuStock:index, page: 1 }
    requirements:
        page:  \d+
        
kg_beekeeping_management_add_lieuStock:
    path:      /lieuStock/nouveau-lieuStock
    defaults:  { _controller: KGBeekeepingManagementBundle:LieuStock:add }
    
kg_beekeeping_management_view_lieuStock:
    path:      /lieuStock/affichage-lieuStock/{id}
    defaults:  { _controller: KGBeekeepingManagementBundle:LieuStock:view }
    requirements:
        id: \d+            