kg_beekeeping_management_home_exploitation:
    path:      /exploitation
    defaults:  { _controller: KGBeekeepingManagementBundle:Exploitation:index }
        
kg_beekeeping_management_home_rucher:
    path:      /rucher/{page}
    defaults:  { _controller: KGBeekeepingManagementBundle:Rucher:index, page: 1 }
    requirements:
        page:  \d+
        
kg_beekeeping_management_add_rucher:
    path:      /rucher/nouveau-rucher
    defaults:  { _controller: KGBeekeepingManagementBundle:Rucher:add }
    
kg_beekeeping_management_view_rucher:
    path:      /rucher/affichage-rucher/{id}
    defaults:  { _controller: KGBeekeepingManagementBundle:Rucher:view }
    requirements:
        id: \d+
    