services:
    kg_beekeeping_management.twig.trie_emplacement_par_ruche_extension:
        class: KG\BeekeepingManagementBundle\Twig\Extension\TrieEmplacementParRuche
        tags:
            -  { name: twig.extension }