services:
    kg_beekeeping_management.twig.trie_emplacement_par_ruche_extension:
        class: KG\BeekeepingManagementBundle\Twig\Extension\TrieEmplacementParRuche
        tags:
            -  { name: twig.extension }
    kg_beekeeping_management.validator.checkmail:
        class: KG\BeekeepingManagementBundle\Validator\CheckMailValidator
        arguments:
            entityManager: @doctrine.orm.entity_manager
        tags:
            -  { name: validator.constraint_validator, alias: kg_beekeeping_management_checkmail } 